apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktehdwudg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktehdwudg
  template:
    metadata:
      labels:
        app: ktehdwudg
    spec:
      containers:
      - image: okteto.dev/ktehdwudg:latest
        name: ktehdwudg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: ""
        - name: Vless_UUID
          value: "bfefa8c1-ea50-44ef-b1d0-f48ecd6056b6"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "bfefa8c1-ea50-44ef-b1d0-f48ecd6056b6"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
